### ISSUE TITLE
Any reason install ca-certificates in final docker image?

### ISSUE THREAD

**Issue by trim21** [craigpastro/pg_uuidv7#40]
https://github.com/craigpastro/pg_uuidv7/blob/85f460224b46a2aec29506eb688955821ad5969b/Dockerfile#L40

Is it required by uuid extension?

**Comment by craigpastro** [comment]
Hello! Interesting. I thought it was needed for some reason. Probably copied it from somewhere. It seems to work without it so I removed it. Thank you!
